### PR TITLE
fix: do not add EPEL repository on Fedora

### LINKED ISSUE #1524: Running Fedora servers I get some failed dnf repository request
**Describe the bug**
running ./prereqs.sh on fedora 36 server throws non blocking error 
`Status code: 404 for https://dl.fedoraproject.org/pub/epel/epel-release-latest-36.noarch.rpm `

**To Reproduce**
1. Go to  fedora 36 run `curl -sS -o prereqs.sh https://raw.githubusercontent.com/cardano-community/guild-operators/master/scripts/cnode-helper-scripts/prereqs.sh`
2. See error `Status code: 404 for https://dl.fedoraproject.org/pub/epel/epel-release-latest-36.noarch.rpm `

**Expected behavior**
no error or warning, and should not try to install epel-release on fedora

**Version:**
 - OS:Fedora 36
 - Product version:
 - Cardano Node version: any
 - Network you're connecting to: any

**Context**
- `/home/cardano/.cabal/bin/cardano-node: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`
-  `Package openssl-1:3.0.5-1.fc36.x86_64 is already installed.`
- `Package openssl-devel-1:3.0.5-1.fc36.x86_64 is already installed.`

### PR DESCRIPTION
**Pull request by mkungla**
Fedora does not need EPEL repository, all prereqs are met with official repos.

closes #1524

### CODE REVIEW

File: scripts/cnode-helper-scripts/prereqs.sh [hunk 1]
```diff
@@ -170,6 +170,16 @@ if [[ "${INTERACTIVE}" = 'Y' ]]; then
...
 fi
 
+# Description : Add epel repository when needed
+#             : $1 = DISTRO
+#             : $2 = Epel repository VERSION_ID
+#             : $3 = pkg_opts for repo install
+add_epel_repository() {
+  if [[ "${1}" =~ Fedora ]]; then return; fi
+  echo "  Enabling epel repository..."
+  ! grep -q ^epel <<< "$(yum repolist)" && $sudo yum ${2} install https://dl.fedoraproject.org/pub/epel/epel-release-latest-"${3}".noarch.rpm > /dev/null
```
Comment (rdlrt) [inline scripts/cnode-helper-scripts/prereqs.sh:180]: $2 and $3 needs swapping here in yum command?

Comment (mkungla) [reply scripts/cnode-helper-scripts/prereqs.sh:180]: my bad

**Comment by mkungla** [comment]
@rdlrt I dunno what's about these failing tests? Should I address these in this PR?

**Comment by rdlrt** [comment]
> @rdlrt I dunno what's about these failing tests? Should I address these in this PR?

I think those are expected atm - as it uses cardano-community in the URL instead of account of PR, will fix it in a seperate PR

**Review by rdlrt — APPROVED** [review]

File: scripts/cnode-helper-scripts/prereqs.sh [hunk 2]
```diff
@@ -217,7 +227,7 @@ if [ "$WANT_BUILD_DEPS" = 'Y' ]; then
       pkg_opts="${pkg_opts} --allowerasing"
       pkg_list="${pkg_list} libusbx ncurses-compat-libs pkgconf-pkg-config srm"
     fi
-    ! grep -q ^epel <<< "$(yum repolist)" && $sudo yum ${pkg_opts} install https://dl.fedoraproject.org/pub/epel/epel-release-latest-"${VERSION_ID}".noarch.rpm > /dev/null
+    add_epel_repository "${DISTRO}" "${VERSION_ID}" "${pkg_opts}"
     $sudo yum ${pkg_opts} install ${pkg_list} > /dev/null;rc=$?
```
Comment (rdlrt) [inline scripts/cnode-helper-scripts/prereqs.sh:231]: actually this line would need to be removed too, as it is being called in function
